### ISSUE TITLE
On using CMSIS DSP Library

### ISSUE THREAD

**Issue by juanmed** [lyf44/Custom-Flight-Controller#1]
Hi,

Thanks for sharing your code. I also read all your blogposts and they are resourceful and easy to understand. I wanted to kindly ask your comments, design choices and experience using the CMSIS DPS Library for linear algebra on the STM32. 

I am to implement a position and orientation controller based on [this](https://arxiv.org/pdf/1003.2005.pdf) and [this](https://ieeexplore.ieee.org/document/8118153).  Apart from vector-vector and matrix-vector operations, the inverse, trace, and many other operations are required. I would like to use an adequate linear algebra library before making an implementation and I think your feedback will be very helpful.

Thanks!

**Comment by lyfkyle** [comment]
You can definitely use CMSIS DSP Library, but personally I prefer Eigen as its syntax is more intuitive and it is more powerful. However, I failed to compile Eigen on STM32, maybe you could give it a try.
